# Generated by Django 2.1.1 on 2020-02-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='potrfolio_site',
            new_name='portfolio_site',
        ),
    ]
